# Generated by Django 3.2.12 on 2022-02-17 15:11

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_name', models.CharField(max_length=4, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('wikipedia_url', models.URLField(blank=True, null=True)),
                ('temperament', models.CharField(max_length=100)),
                ('origin', django_countries.fields.CountryField(max_length=2)),
                ('life_span', models.CharField(max_length=20)),
                ('adaptability', models.IntegerField()),
                ('affection_level', models.IntegerField()),
                ('child_friendly', models.IntegerField()),
                ('grooming', models.IntegerField()),
                ('intelligence', models.IntegerField()),
                ('health_issues', models.IntegerField()),
                ('social_needs', models.IntegerField()),
                ('stranger_friendly', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CatImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_image', models.URLField(unique=True)),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catwiki_web.cat')),
            ],
        ),
    ]
