# Generated by Django 3.2.12 on 2022-02-18 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catwiki_web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='catimage',
            name='main_image',
            field=models.BooleanField(default=False),
        ),
    ]
