# Generated by Django 3.2.12 on 2022-02-21 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catwiki_web', '0002_catimage_main_image'),
    ]

    operations = [
        migrations.RunSQL(
            """UPDATE catwiki_web_catimage SET main_image = True WHERE cat_id = (SELECT id FROM catwiki_web_cat WHERE id_name = 'beng') AND url_image = 'https://cdn2.thecatapi.com/images/ZocD-pQxd.jpg'; """,
        ),
        migrations.RunSQL(
            """UPDATE catwiki_web_catimage SET main_image = False WHERE cat_id = (SELECT id FROM catwiki_web_cat WHERE id_name = 'beng') AND url_image = 'https://cdn2.thecatapi.com/images/O3btzLlsO.png'; """,
        )
    ]
